apiVersion: v1
kind: Pod
metadata:
  name: pod-expert-day2
  labels:
    app: giropops
    aula: day2
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: logs-volume
      mountPath: /var/log/nginx

  - name: sidecar-container
    image: busybox
    command: ["sh", "-c", "while true; do date >> /var/log/nginx/date.log; sleep 5; done"]
    volumeMounts:
    - name: logs-volume
      mountPath: /var/log/nginx

  volumes:
  - name: logs-volume
    emptyDir: {}
